wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 4
initialization:
  value: Xavier
learning_rate:
  value: 0.0001
optimizer:
  value: momentum
weight_decay:
  value: 0.5
