_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": darwin-arm64
activation:
    value: tanh
batch_size:
    value: 16
dataset:
    value: fashion_mnist
epochs:
    value: 10
hidden_layer_sizes:
    value: 128
hidden_layers:
    value: 4
initialization:
    value: random
learning_rate:
    value: 0.001
optimizer:
    value: nadam
weight_decay:
    value: 0
