wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
beta:
  value: 0.5
beta1:
  value: 0.999
beta2:
  value: 9
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-06
hidden_layer_sizes:
  value: 32
hidden_layers:
  value: 5
initialization:
  value: random
learning_rate:
  value: 0.0001
loss_function:
  value: cross_entropy
momentum:
  value: 0.9
optimizer:
  value: sgd
weight_decay:
  value: 0
weight_init:
  value: random
