wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_layer_sizes:
  value: 32
hidden_layers:
  value: 4
initialization:
  value: random
learning_rate:
  value: 0.0001
optimizer:
  value: sgd
weight_decay:
  value: 0.0005
