wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_layer_sizes:
  value: 64
hidden_layers:
  value: 5
initialization:
  value: Xavier
learning_rate:
  value: 0.0001
optimizer:
  value: nesterov
weight_decay:
  value: 0.0005
