_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.11.7
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 14
                - 23
                - 55
            "4": 3.11.7
            "5": 0.19.7
            "8":
                - 1
                - 5
            "12": 0.19.7
            "13": darwin-arm64
        visualize:
            conf_mat:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: conf_mat_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
activation:
    value: tanh
batch_size:
    value: 32
dataset:
    value: fashion_mnist
epochs:
    value: 5
hidden_layer_sizes:
    value: 128
hidden_layers:
    value: 5
initialization:
    value: random
learning_rate:
    value: 0.001
optimizer:
    value: momentum
weight_decay:
    value: 0.5
