wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta:
  value: 0.5
beta1:
  value: 0.999
beta2:
  value: 0.999
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-06
hidden_layer_sizes:
  value: 64
hidden_layers:
  value: 5
initialization:
  value: Xavier
learning_rate:
  value: 0.0001
loss_function:
  value: mean_squared_error
momentum:
  value: 0.5
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: random
