wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 9
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-06
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 5
initialization:
  value: Xavier
learning_rate:
  value: 0.0001
loss_function:
  value: mean_squared_error
momentum:
  value: 0.5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: xavier
