wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 9
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 4
initialization:
  value: random
learning_rate:
  value: 0.001
loss_function:
  value: cross_entropy
momentum:
  value: 0.9
optimizer:
  value: nadam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
