wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
beta:
  value: 0.9
beta1:
  value: 0.999
beta2:
  value: 9
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 5
initialization:
  value: random
learning_rate:
  value: 0.001
loss_function:
  value: mean_squared_error
momentum:
  value: 0.9
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: random
