wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.5
beta1:
  value: 0.999
beta2:
  value: 0
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-06
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 4
initialization:
  value: random
learning_rate:
  value: 0.001
loss_function:
  value: mean_squared_error
momentum:
  value: 0.5
optimizer:
  value: momentum
weight_decay:
  value: 0.0005
weight_init:
  value: random
