wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.9
beta2:
  value: 0
dataset:
  value: fashion_mnist
epochs:
  value: 10
epsilon:
  value: 1.0e-06
hidden_layer_sizes:
  value: 32
hidden_layers:
  value: 4
initialization:
  value: random
learning_rate:
  value: 0.001
loss_function:
  value: mean_squared_error
momentum:
  value: 0.5
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: random
