wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
beta:
  value: 0.5
beta1:
  value: 0.999
beta2:
  value: 9
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_layer_sizes:
  value: 64
hidden_layers:
  value: 5
initialization:
  value: Xavier
learning_rate:
  value: 0.001
loss_function:
  value: mean_squared_error
momentum:
  value: 0.5
optimizer:
  value: nesterov
weight_decay:
  value: 0.5
weight_init:
  value: xavier
