wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.999
beta2:
  value: 0
dataset:
  value: fashion_mnist
epochs:
  value: 5
epsilon:
  value: 1.0e-08
hidden_layer_sizes:
  value: 64
hidden_layers:
  value: 4
initialization:
  value: random
learning_rate:
  value: 0.001
loss_function:
  value: cross_entropy
momentum:
  value: 0.9
optimizer:
  value: momentum
weight_decay:
  value: 0
weight_init:
  value: random
