wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_layer_sizes:
  value: 64
hidden_layers:
  value: 3
initialization:
  value: random
learning_rate:
  value: 0.001
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
