wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 5
initialization:
  value: random
learning_rate:
  value: 0.0001
optimizer:
  value: nadam
weight_decay:
  value: 0
