wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 64
dataset:
  value: fashion_mnist
epochs:
  value: 10
hidden_layer_sizes:
  value: 32
hidden_layers:
  value: 4
initialization:
  value: Xavier
learning_rate:
  value: 0.001
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
