wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_layer_sizes:
  value: 128
hidden_layers:
  value: 3
initialization:
  value: random
learning_rate:
  value: 0.001
optimizer:
  value: nadam
weight_decay:
  value: 0
