wandb_version: 1

activation:
  value: ReLU
batch_size:
  value: 32
dataset:
  value: fashion_mnist
epochs:
  value: 5
hidden_layer_sizes:
  value: 32
hidden_layers:
  value: 3
initialization:
  value: Xavier
learning_rate:
  value: 0.0001
optimizer:
  value: adam
weight_decay:
  value: 0
